<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-19T17:07:28 IST" name="Suite" finished-at="2023-07-19T17:07:45 IST" duration-ms="16843">
    <groups>
    </groups>
    <test started-at="2023-07-19T17:07:28 IST" name="Test" finished-at="2023-07-19T17:07:45 IST" duration-ms="16843">
      <class name="api.test.UserTests2">
        <test-method is-config="true" signature="setUP()[pri:0, instance:api.test.UserTests2@71238fc2]" started-at="2023-07-19T17:07:29 IST" name="setUP" finished-at="2023-07-19T17:07:30 IST" duration-ms="1299" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUP -->
        <test-method signature="postUser_TC()[pri:1, instance:api.test.UserTests2@71238fc2]" started-at="2023-07-19T17:07:30 IST" name="postUser_TC" finished-at="2023-07-19T17:07:35 IST" duration-ms="4997" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- postUser_TC -->
        <test-method signature="readUserbyName()[pri:2, instance:api.test.UserTests2@71238fc2]" started-at="2023-07-19T17:07:35 IST" name="readUserbyName" finished-at="2023-07-19T17:07:37 IST" duration-ms="1775" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readUserbyName -->
        <test-method signature="UpdateDeatisOfUser()[pri:3, instance:api.test.UserTests2@71238fc2]" started-at="2023-07-19T17:07:37 IST" name="UpdateDeatisOfUser" finished-at="2023-07-19T17:07:42 IST" duration-ms="5831" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- UpdateDeatisOfUser -->
        <test-method signature="DelterUserByNmae()[pri:4, instance:api.test.UserTests2@71238fc2]" started-at="2023-07-19T17:07:42 IST" name="DelterUserByNmae" finished-at="2023-07-19T17:07:45 IST" duration-ms="2391" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [300] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [300] but found [200]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at api.test.UserTests2.DelterUserByNmae(UserTests2.java:76)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DelterUserByNmae -->
      </class> <!-- api.test.UserTests2 -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
